version: '3.8'
services:
  mirai:
    container_name: mirai
    image: dousha99/miraicle
    volumes:
      - 'mcl:/app/mcl/'
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true

volumes:
  mcl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mcl

